//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::StatusEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub username: String,
    pub subscribed_at: DateTimeWithTimeZone,
    pub status: StatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::subscription_tokens::Entity")]
    SubscriptionTokens,
}

impl Related<super::subscription_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
