application_config:
  port: 15000
db_settings:
  host: "localhost"
  port: 5432
  username: postgres
  password: postgres
  database: mail-server
email_config:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 3000