application_config:
  port: 8080
db_settings:
  host: "localhost"
  port: 5432
  username: postgres
  password: postgres
  database: mail-server
email_config:
  base_url: "localhost"
  sender_email: "test@gmail.com"