name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: 测试和检查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: 检查代码格式
        run: cargo fmt --all -- --check

      - name: 运行 Clippy
        run: cargo clippy --all-targets --all-features

      - name: 运行测试
        run: cargo test --all-features

      - name: 检查文档
        run: cargo doc --no-deps --all-features

      - name: 运行基准测试
        run: cargo bench --no-run

      - name: 构建发布版本
        run: cargo build --release --all-features

  coverage:
    name: 代码覆盖率
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: 安装 cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: 运行 Tarpaulin
        run: cargo tarpaulin --out Html

      - name: 上传覆盖率报告
      - uses: actions/upload-artifact@v4.4.1
        with:
          name: coverage-report
          path: tarpaulin-report.html
      # - name: 上传到 Codecov
      #   uses: codecov/codecov-action@v3

  security_audit:
    name: 安全审计
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: 安装 cargo-audit
        run: cargo install cargo-audit
      - name: 运行 cargo-audit
        run: cargo audit
